// <auto-generated />
using System;
using BussinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussinessObjects.Migrations
{
    [DbContext(typeof(CiAuctionContext))]
    [Migration("20240305082836_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BussinessObjects.DepositRequest", b =>
                {
                    b.Property<Guid>("DepositRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("depositRequestId");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("OrchidId")
                        .HasColumnType("char(36)")
                        .HasColumnName("orchidId");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ownerId");

                    b.HasKey("DepositRequestId");

                    b.HasIndex("OrchidId");

                    b.HasIndex("UserId");

                    b.ToTable("deposit_request");
                });

            modelBuilder.Entity("BussinessObjects.Orchid", b =>
                {
                    b.Property<Guid>("OrchidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("orchidId");

                    b.Property<int>("DepositedStatus")
                        .HasColumnType("int")
                        .HasColumnName("depositedStatus");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("imageUrl");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ownerId");

                    b.HasKey("OrchidId");

                    b.HasIndex("UserId");

                    b.ToTable("orchid");
                });

            modelBuilder.Entity("BussinessObjects.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("userId");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("walletAddress");

                    b.HasKey("UserId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("BussinessObjects.DepositRequest", b =>
                {
                    b.HasOne("BussinessObjects.Orchid", "Orchid")
                        .WithMany("DepositRequests")
                        .HasForeignKey("OrchidId");

                    b.HasOne("BussinessObjects.User", "User")
                        .WithMany("DepositRequests")
                        .HasForeignKey("UserId");

                    b.Navigation("Orchid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BussinessObjects.Orchid", b =>
                {
                    b.HasOne("BussinessObjects.User", "User")
                        .WithMany("Orchids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BussinessObjects.Orchid", b =>
                {
                    b.Navigation("DepositRequests");
                });

            modelBuilder.Entity("BussinessObjects.User", b =>
                {
                    b.Navigation("DepositRequests");

                    b.Navigation("Orchids");
                });
#pragma warning restore 612, 618
        }
    }
}
